
services:
  whoami:
    image: traefik/whoami
    labels:
      - "traefik.http.routers.whoami.rule=Host(`whoami.localhost`)"

      # needs to register an HTTP router here
      # learn more at https://doc.traefik.io/traefik/reference/routing-configuration/http/routing/router/#configuration-example
      - "traefik.http.routers.whoami.middlewares=this_is_my_custom_middleware,this_is_my_external_auth_middleware"

      - "traefik.http.middlewares.this_is_my_custom_middleware.headers.customrequestheaders.X-Dummy-Request-Header=traefik"
      - "traefik.http.middlewares.this_is_my_custom_middleware.headers.customresponseheaders.X-Dummy-Response-Header=traefik"
      - "traefik.http.middlewares.this_is_my_external_auth_middleware.forwardauth.address=http://auth.localhost/login"